#!/bin/sh
# Generate a .env with real secrets. Idempotent: never overwrites an existing
# file, so re-running it cannot rotate your database password out from under a
# running Postgres volume.
set -eu

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists — leaving it alone."
  exit 0
fi

# Prefer openssl; fall back to /dev/urandom so this works on a bare container.
gen() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

cat > .env <<ENVEOF
# Generated by scripts/setup-env.sh — do not commit this file.

# Postgres. Only the hub reaches it (the port is not published), but a unique
# password still keeps a compromised container from being a free lateral hop.
POSTGRES_PASSWORD=$(gen)

# Host port for the web UI and the sync endpoint.
HUB_PORT=7500

# Shared token for the optional standalone daemon:
#   docker compose --profile standalone up -d
FKIT_TOKEN=$(gen)
FKITD_PORT=7420

# RUST_LOG=fkit_hub=debug,tower_http=info
ENVEOF

chmod 600 .env
echo "Wrote .env with generated secrets (mode 600)."
